export const CanalSchema = {
    name: 'Canal',
    primaryKey: 'stream_id',
    properties: {
        num: 'string',
        name: 'string',
        stream_id: 'string',
        stream_icon: 'string?',
        category_id: 'string',
        category_ids: 'string[]',
        link: 'string',
        favorito: 'bool',
        visto: 'bool',
    },
};

export const PeliculaSchema = {
    name: 'Pelicula',
    primaryKey: 'stream_id',
    properties: {
        num: 'string',
        name: 'string',
        title: 'string?',
        year: 'string?',
        stream_id: 'string',
        stream_icon: 'string?',
        rating: 'string',
        plot: 'string?',
        genre: 'string?',
        release_date: 'string?',
        episode_run_time: 'string?',
        category_id: 'string',
        category_ids: 'string[]',
        tmdb_id: 'string?',
        backdrop_path: 'string?',
        original_title: 'string?',
        overview: 'string?',
        poster_path: 'string?',
        runtime: 'string?',
        genres: 'string?',
        vote_average: 'string?',
        cast: 'string?',
        link: 'string',
        favorito: 'bool',
        visto: 'bool',
    },
};

export const EpisodioSchema = {
    name: 'Episodio',
    embedded: true,
    properties: {
        id: 'string',
        episode_num: 'string',
        title: 'string',
        plot: 'string?',
        duration_secs: 'string',
        movie_image: 'string?',
        rating: 'string',
        season: 'string',
        id_serie: 'string',
        link: 'string',
        visto: 'bool',
    },
};

export const TemporadaSchema = {
    name: 'Temporada',
    embedded: true,
    properties: {
        numero: 'string',
        episodios: { type: 'list', objectType: 'Episodio' },
    },
};

export const SerieSchema = {
    name: 'Serie',
    primaryKey: 'series_id',
    properties: {
        num: 'string',
        name: 'string',
        title: 'string?',
        year: 'string?',
        series_id: 'string',
        cover: 'string?',
        plot: 'string?',
        genre: 'string?',
        release_date: 'string?',//
        rating: 'string?',
        backdrop_path: 'string?',
        category_id: 'string',
        category_ids: 'string[]',
        tmdb_id: 'string?',
        original_name: 'string?',
        backdrop_path_aux: 'string?',
        vote_average: 'string?',
        poster_path: 'string?',
        genres: 'string?',
        overview: 'string?',
        cast: 'string?',
        temporadas: { type: 'list', objectType: 'Temporada' },
        favorito: 'bool',
        visto: 'bool',
        saga: 'bool',
    },
};