export const CanalSchema = {
    name: 'Canal',
    primaryKey: 'stream_id',
    properties: {
        num: 'int',
        name: 'string',
        stream_id: 'int',
        stream_icon: 'string?',
        category_id: 'string',
        category_ids: 'int[]',
        link: 'string',
        favorito: 'bool',
        visto: 'bool',
    },
};

export const PeliculaSchema = {
    name: 'Pelicula',
    primaryKey: 'stream_id',
    properties: {
        num: 'int',
        name: 'string',
        title: 'string',
        year: 'string?',
        stream_id: 'int',
        stream_icon: 'string?',
        rating: 'double',
        plot: 'string?',
        genre: 'string?',
        release_date: 'string?',
        episode_run_time: 'string?',
        category_id: 'string',
        category_ids: 'int[]',
        tmdb_id: 'int?',
        backdrop_path: 'string?',
        original_title: 'string?',
        overview: 'string?',
        poster_path: 'string?',
        runtime: 'int?',
        genres: 'string?',
        vote_average: 'double?',
        cast: 'string?',
        link: 'string',
        favorito: 'bool',
        visto: 'bool',
    },
};

export const EpisodioSchema = {
    name: 'Episodio',
    embedded: true,
    properties: {
        id: 'string',
        episode_num: 'string',
        title: 'string',
        plot: 'string?',
        duration_secs: 'int',
        movie_image: 'string?',
        rating: 'string',
        season: 'int',
        id_serie: 'int',
        link: 'string',
        visto: 'bool',
    },
};

export const TemporadaSchema = {
  name: 'Temporada',
  embedded: true,
  properties: {
    numero: 'string',
    episodios: { type: 'list', objectType: 'Episodio' },
  },
};

export const SerieSchema = {
    name: 'Serie',
    primaryKey: 'series_id',
    properties: {
        num: 'int',
        name: 'string',
        title: 'string',
        year: 'string?',
        series_id: 'int',
        cover: 'string?',
        plot: 'string?',
        genre: 'string?',
        release_date: 'string',
        rating: 'string?',
        backdrop_path: 'string?',
        category_id: 'string',
        category_ids: 'int[]',
        tmdb_id: 'int?',
        original_name: 'string?',
        backdrop_path_aux: 'string?',
        vote_average: 'double?',
        poster_path: 'string?',
        genres: 'string?',
        overview: 'string?',
        cast: 'string?',
        temporadas: { type: 'list', objectType: 'Temporada' },
        favorito: 'bool',
        visto: 'bool',
        saga: 'bool',
    },
};
